// src/data/jobs.js
export const jobData = [
  {
    id: 1,
    title: 'User Experience Designer',
    location: 'London, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Design + User Experience + Research',
    ctc: { min: 40000, max: 60000 }
  },
  {
    id: 2,
    title: 'Front-End Developer',
    location: 'Manchester, UK',
    type: 'Full-Time',
    experience: '3yrs - 5yrs',
    skills: 'Coding + HTML/CSS + JavaScript',
    ctc: { min: 35000, max: 55000 },
  },
  {
    id: 3,
    title: 'Customer Support Executive',
    location: 'Chelsea, UK',
    type: 'Full-Time',
    experience: '3yrs - 6yrs',
    skills: 'Support + Communication + Problem Solving',
    ctc: { min: 30000, max: 50000 },
  },
  {
    id: 4,
    title: 'Digital Marketing Specialist',
    location: 'Liverpool, UK',
    type: 'Full-Time',
    experience: '8yrs - 10yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 50000, max: 70000 },
  },
  {
    id: 5,
    title: 'Product Manager',
    location: 'New York, USA',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Product + Strategy + Leadership',
    ctc: { min: 80000, max: 120000 },
  },
  {
    id: 6,
    title: 'Graphic Designer',
    location: 'Leeds, UK',
    type: 'Internship',
    experience: '1yrs - 1.5yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 18000, max: 22000 },
  },
  {
    id: 7,
    title: 'Warehouse Associate',
    location: 'Liverpool, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Logistics + Inventory + Operations',
    ctc: { min: 25000, max: 35000 },
  },
  {
    id: 8,
    title: 'Customer Support Representative',
    location: 'Manchester, UK',
    type: 'Full-Time',
    experience: '3yrs - 5yrs',
    skills: 'Support + Communication + Problem Solving',
    ctc: { min: 28000, max: 45000 },
  },
  {
    id: 9,
    title: 'Digital Marketing Manager',
    location: 'London, UK',
    type: 'Full-Time',
    experience: '8yrs - 10yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 60000, max: 80000 },
  },
  {
    id: 10,
    title: 'Product Designer',
    location: 'New York, USA',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 85000, max: 125000 },
  },
  {
    id: 11,
    title: 'Graphic Designer',
    location: 'Leeds, UK',
    type: 'Internship',
    experience: '1yrs - 1.5yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 18000, max: 22000 },
  },
  {
    id: 12,
    title: 'Content Writer',
    location: 'Glasgow, UK',
    type: 'Part-Time',
    experience: '2yrs - 3yrs',
    skills: 'Writing + Content + Research',
    ctc: { min: 15000, max: 25000 },
  },
  {
    id: 13,
    title: 'UX Designer',
    location: 'Edinburgh, UK',
    type: 'Full-Time',
    experience: '5yrs - 7yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 45000, max: 65000 },
  },
  {
    id: 14,
    title: 'Account Manager',
    location: 'Birmingham, UK',
    type: 'Full-Time',
    experience: '3yrs - 5yrs',
    skills: 'Sales + Marketing + Management',
    ctc: { min: 40000, max: 60000 },
  },
  {
    id: 15,
    title: 'Software Engineer',
    location: 'Cardiff, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Engineering + Coding + Development',
    ctc: { min: 50000, max: 70000 },
  },
  {
    id: 16,
    title: 'Product Manager',
    location: 'Sheffield, UK',
    type: 'Full-Time',
    experience: '8yrs - 10yrs',
    skills: 'Management + Leadership + Strategy',
    ctc: { min: 70000, max: 90000 },
  },
  {
    id: 17,
    title: 'Digital Marketing Specialist',
    location: 'Bristol, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Marketing + Advertising + Social Media',
    ctc: { min: 40000, max: 60000 },
  },
  {
    id: 18,
    title: 'Data Analyst',
    location: 'Nottingham, UK',
    type: 'Full-Time',
    experience: '2yrs - 3yrs',
    skills: 'Data + Analytics + Research',
    ctc: { min: 30000, max: 40000 },
  },
  {
    id: 19,
    title: 'Graphic Designer',
    location: 'Newcastle, UK',
    type: 'Internship',
    experience: '1yrs - 1.5yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 18000, max: 22000 },
  },
  {
    id: 20,
    title: 'Customer Support Specialist',
    location: 'Leeds, UK',
    type: 'Part-Time',
    experience: '2yrs - 3yrs',
    skills: 'Support + Communication + Problem Solving',
    ctc: { min: 20000, max: 30000 },
  },
  {
    id: 21,
    title: 'UX Designer',
    location: 'Southampton, UK',
    type: 'Full-Time',
    experience: '5yrs - 7yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 45000, max: 65000 },
  },
  {
    id: 22,
    title: 'Software Engineer',
    location: 'Portsmouth, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Engineering + Coding + Development',
    ctc: { min: 50000, max: 70000 },
  },
  {
    id: 23,
    title: 'Product Manager',
    location: 'Oxford, UK',
    type: 'Full-Time',
    experience: '8yrs - 10yrs',
    skills: 'Management + Leadership + Strategy',
    ctc: { min: 70000, max: 90000 },
  },
  {
    id: 24,
    title: 'Digital Marketing Specialist',
    location: 'Cambridge, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Marketing + Advertising + Social Media',
    ctc: { min: 40000, max: 60000 },
  },
  {
    id: 25,
    title: 'Data Analyst',
    location: 'Brighton, UK',
    type: 'Full-Time',
    experience: '2yrs - 3yrs',
    skills: 'Data + Analytics + Research',
    ctc: { min: 30000, max: 40000 },
  },
  {
    id: 26,
    title: 'Graphic Designer',
    location: 'Swansea, UK',
    type: 'Internship',
    experience: '1yrs - 1.5yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 18000, max: 22000 },
  },
  {
    id: 27,
    title: 'Customer Support Specialist',
    location: 'Norwich, UK',
    type: 'Part-Time',
    experience: '2yrs - 3yrs',
    skills: 'Support + Communication + Problem Solving',
    ctc: { min: 20000, max: 30000 },
  },
  {
    id: 28,
    title: 'UX Designer',
    location: 'Hull, UK',
    type: 'Full-Time',
    experience: '5yrs - 7yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 45000, max: 65000 },
  },
  {
    id: 29,
    title: 'Software Engineer',
    location: 'Plymouth, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Engineering + Coding + Development',
    ctc: { min: 50000, max: 70000 },
  },
  {
    id: 30,
    title: 'Product Manager',
    location: 'Lincoln, UK',
    type: 'Full-Time',
    experience: '8yrs - 10yrs',
    skills: 'Management + Leadership + Strategy',
    ctc: { min: 70000, max: 90000 },
  },
  {
    id: 31,
    title: 'Digital Marketing Specialist',
    location: 'York, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Marketing + Advertising + Social Media',
    ctc: { min: 40000, max: 60000 },
  },
  {
    id: 32,
    title: 'Data Analyst',
    location: 'Durham, UK',
    type: 'Full-Time',
    experience: '2yrs - 3yrs',
    skills: 'Data + Analytics + Research',
    ctc: { min: 30000, max: 40000 },
  },
  {
    id: 33,
    title: 'Graphic Designer',
    location: 'Newport, UK',
    type: 'Internship',
    experience: '1yrs - 1.5yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 18000, max: 22000 },
  },
  {
    id: 34,
    title: 'Customer Support Specialist',
    location: 'Exeter, UK',
    type: 'Part-Time',
    experience: '2yrs - 3yrs',
    skills: 'Support + Communication + Problem Solving',
    ctc: { min: 20000, max: 30000 },
  },
  {
    id: 35,
    title: 'UX Designer',
    location: 'Truro, UK',
    type: 'Full-Time',
    experience: '5yrs - 7yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 45000, max: 65000 },
  },
  {
    id: 36,
    title: 'Software Engineer',
    location: 'Gloucester, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Engineering + Coding + Development',
    ctc: { min: 50000, max: 70000 },
  },
  {
    id: 37,
    title: 'Product Manager',
    location: 'Chester, UK',
    type: 'Full-Time',
    experience: '8yrs - 10yrs',
    skills: 'Management + Leadership + Strategy',
    ctc: { min: 70000, max: 90000 },
  },
  {
    id: 38,
    title: 'Digital Marketing Specialist',
    location: 'Cheltenham, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Marketing + Advertising + Social Media',
    ctc: { min: 40000, max: 60000 },
  },
  {
    id: 39,
    title: 'Data Analyst',
    location: 'Bath, UK',
    type: 'Full-Time',
    experience: '2yrs - 3yrs',
    skills: 'Data + Analytics + Research',
    ctc: { min: 30000, max: 40000 },
  },
  {
    id: 40,
    title: 'Graphic Designer',
    location: 'Swindon, UK',
    type: 'Internship',
    experience: '1yrs - 1.5yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 18000, max: 22000 },
  },
  {
    id: 41,
    title: 'Customer Support Specialist',
    location: 'Salisbury, UK',
    type: 'Part-Time',
    experience: '2yrs - 3yrs',
    skills: 'Support + Communication + Problem Solving',
    ctc: { min: 20000, max: 30000 },
  },
  {
    id: 42,
    title: 'UX Designer',
    location: 'Southend-on-Sea, UK',
    type: 'Full-Time',
    experience: '5yrs - 7yrs',
    skills: 'Designer + User Experience + Research',
    ctc: { min: 45000, max: 65000 },
  },
  {
    id: 43,
    title: 'Software Engineer',
    location: 'Colchester, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Engineering + Coding + Development',
    ctc: { min: 50000, max: 70000 },
  },
  {
    id: 44,
    title: 'Product Manager',
    location: 'Ipswich, UK',
    type: 'Full-Time',
    experience: '8yrs - 10yrs',
    skills: 'Management + Leadership + Strategy',
    ctc: { min: 70000, max: 90000 },
  },
  {
    id: 45,
    title: 'Digital Marketing Specialist',
    location: 'Norwich, UK',
    type: 'Full-Time',
    experience: '4yrs - 6yrs',
    skills: 'Marketing + Advertising + Social Media',
    ctc: { min: 40000, max: 60000 },
  },
  {
    id: 46,
    title: 'Data Analyst',
    location: 'Peterborough, UK',
    type: 'Full-Time',
    experience: '2yrs - 3yrs',
    skills: 'Data + Analytics + Research',
    ctc: { min: 30000, max: 40000 },
  },
  {
    id: 47,
    title: 'Graphic Designer',
    location: 'Cambridge, UK',
    type: 'Internship',
    experience: '2yrs - 3yrs',
    skills: 'Data + Analytics + Research',
    ctc: { min: 20000, max: 25000 },
  }
  // Add more as needed
];


export default jobData;